version: '2'
services:
  grafana:
    image: grafana/grafana
    container_name: dev-grafana-dashboard
    environment:
    - GF_PATHS_DATA	/opt/grafana
    - GF_PATHS_LOGS	/opt/log/grafana
    - GF_PATHS_PLUGINS /opt/grafana/plugins
    - GF_PATHS_PROVISIONING	/etc/grafana/provisioning
    ports:
      - 80:3000
    volumes: 
      - ./data/grafana:/opt/grafana/data
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/custom.ini:/etc/grafana/grafana.ini

    depends_on:
      - graphite
  statsd:
    build: ./statsd
    container_name: dev-statsd
    environment: 
      - GRAPHITE_PORT_2003_TCP_ADDR=graphite
    ports:
      - "8125:8125/udp"
      - "8126:8126"
  graphite:
    build: ./graphite
    # image: myoperator/graphite_statsd
    container_name: dev-graphite-carbon
    ports:
      - "8080:80"
    environment: 
      - GRAPHITE_STATSD_HOST=statsd
    expose: 
      - 8080
      - "2003-2004"
      - "2023-2024"
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./log/graphite:/opt/graphite/storage/log
    depends_on:
      - statsd
